# Generated by Django 5.1.1 on 2024-09-13 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_category_price_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.category'),
        ),
        migrations.AddField(
            model_name='museumimage',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.price'),
        ),
        migrations.AddField(
            model_name='museumimage',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.ticket'),
        ),
    ]
