# Generated by Django 5.1.1 on 2024-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_museumimage_category_museumimage_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_phoneno',
            field=models.BigIntegerField(default=0),
        ),
    ]
