# Generated by Django 5.1.1 on 2024-09-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_ticket_customer_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_age',
            field=models.IntegerField(default=0),
        ),
    ]
